In [115]:
import pandas as pd

## Revised

#### I manually reviewed this dataset in batches of 100 movies. My initial goal was to fill in missing professions, but along the way I found a number of issues with the cast selection and some incorrect character names. Those were corrected manually, so from this point on I use the revised version of the dataset.

In [116]:
romcoms = pd.read_csv("REVISED_romcoms.csv", sep=";")
romcoms.shape

(1987, 17)

### Removing the 2026 movies

In [117]:
romcoms_updated = romcoms.query("startYear != 2026")
romcoms_updated.shape

(1977, 17)

## I initially filtered the movies using IMDb by selecting titles tagged with both Comedy and Romance.

#### However, not every film meeting those criteria was actually a romantic comedy. While reviewing the dataset in batches of 100 movies, I found that many leaned more toward comedy or drama. To speed up the review process, I asked both ChatGPT and Claude to identify films that did not fit the rom-com category—that is, films centered on a main romantic couple, with the romance serving as a central pillar of the narrative. I then manually reviewed their suggestions before removing any titles from the dataset.

In [ ]:
remove_titles = [
    "Adam",
    "Afire",
    "Am I OK?",
    "Away We Go",
    "Beautiful Girls",
    "Best. Christmas. Ever!",
    "Blue Jasmine",
    "Blue Valentine",
    "C'est la vie!",
    "Day of the Wacko",
    "Dear White People",
    "Dr. T & the Women",
    "Dragons Forever",
    "Extract",
    "Factotum",
    "Fallen Leaves",
    "Flora and Son",
    "Flower",
    "Frances Ha",
    "Friends with Money",
    "Full Frontal",
    "Fukrey",
    "Good Bye, Lenin!",
    "Good Grief",
    "Her",
    "Home for the Holidays",
    "Hope and Glory",
    "How to Make an American Quilt",
    "I Love You, Man",
    "Indecent Proposal",
    "Jumpin' Jack Flash",
    "Kicking & Screaming",
    "Last Life in the Universe",
    "Last Night",
    "Man of the Year",
    "Miss You Already",
    "Mother's Day",
    "New York, I Love You",
    "New York Stories",
    "Now and Then",
    "Paris",
    "Paris, je t'aime",
    "Playing by Heart",
    "Puzzle",
    "Results",
    "Romance & Cigarettes",
    "Shortbus",
    "Sideways",
    "Smart People",
    "Someone Great",
    "Steel Magnolias",
    "Storytelling",
    "Take This Waltz",
    "Tallulah",
    "The Diary of a Teenage Girl",
    "The Divorce",
    "The Flintstones",
    "The French Dispatch",
    "The History Boys",
    "The Hollars",
    "The Jane Austen Book Club",
    "The Kids Are All Right",
    "The Meyerowitz Stories",
    "The Perks of Being a Wallflower",
    "The Private Lives of Pippa Lee",
    "The Shape of Things",
    "The Skeleton Twins",
    "The Ten",
    "The War of the Roses",
    "Three Colors: White",
    "Together",
    "Up in the Air",
    "Venus",
    "Weird Science",
    "Wild Wild Punjab",
    "Young People Fucking"
]

In [ ]:
romcoms_final = romcoms_updated[
    ~romcoms["primaryTitle"].isin(remove_titles)
]

/var/folders/qn/0_m8lc7j6hz111kp72r17lnh0000gn/T/ipykernel_15840/3152782209.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  romcoms_final = romcoms_updated[

In [ ]:
romcoms_final.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,ordering,nconst,category,job,characters,profession_final
0,tt0035423,movie,Kate & Leopold,Kate & Leopold,0,2001,\N,118,"Comedy,Fantasy,Romance",6.4,94041,1,nm0000212,actress,\N,Kate McKay,advertising executive
1,tt0035423,movie,Kate & Leopold,Kate & Leopold,0,2001,\N,118,"Comedy,Fantasy,Romance",6.4,94041,2,nm0413168,actor,\N,Leopold,nobleman
2,tt0079579,movie,Moscow Does Not Believe in Tears,Moskva slezam ne verit,0,1980,\N,150,"Comedy,Drama,Romance",8.0,15813,1,nm0018079,actress,\N,Katerina 'Katya' Tikhomirova,manufacturing worker
3,tt0079579,movie,Moscow Does Not Believe in Tears,Moskva slezam ne verit,0,1980,\N,150,"Comedy,Drama,Romance",8.0,15813,2,nm0060692,actor,\N,Georgiy 'Gosha',factory worker
4,tt0080439,movie,The Taming of the Scoundrel,Il bisbetico domato,0,1980,\N,107,"Comedy,Romance",7.6,11472,1,nm0147983,actor,\N,Elia Codogno,farmer

In [ ]:
romcoms_final.shape

(1849, 17)

In [ ]:
romcoms_final["startYear"].dtype

dtype('int64')

In [ ]:
romcoms_final["startYear"].min()
romcoms_final["startYear"].max()

2025

In [ ]:
romcoms_final = romcoms_final.sort_values(
    by=["startYear", "primaryTitle"]
)
romcoms_final

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,ordering,nconst,category,job,characters,profession_final
12,tt0082477,movie,Gregory's Girl,Gregory's Girl,0,1980,\N,91,"Comedy,Drama,Romance",7.1,10068,1,nm0329947,actor,\N,Gregory,student
13,tt0082477,movie,Gregory's Girl,Gregory's Girl,0,1980,\N,91,"Comedy,Drama,Romance",7.1,10068,2,nm0378342,actress,\N,Dorothy,student
2,tt0079579,movie,Moscow Does Not Believe in Tears,Moskva slezam ne verit,0,1980,\N,150,"Comedy,Drama,Romance",8.0,15813,1,nm0018079,actress,\N,Katerina 'Katya' Tikhomirova,manufacturing worker
3,tt0079579,movie,Moscow Does Not Believe in Tears,Moskva slezam ne verit,0,1980,\N,150,"Comedy,Drama,Romance",8.0,15813,2,nm0060692,actor,\N,Georgiy 'Gosha',factory worker
6,tt0081480,movie,Seems Like Old Times,Seems Like Old Times,0,1980,\N,102,"Comedy,Romance",6.7,11862,1,nm0000443,actress,\N,Glenda Parks,lawyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1750,tt33039440,movie,The Wrong Paris,The Wrong Paris,0,2025,\N,105,"Comedy,Drama,Romance",6.1,14590,2,nm4943457,actor,\N,Trey McAllen,rancher
1765,tt35146696,movie,Tu Meri Main Tera Main Tera Tu Meri,Tu Meri Main Tera Main Tera Tu Meri,0,2025,\N,145,"Adventure,Comedy,Romance",4.0,28166,1,nm4449711,actor,\N,Ray,wedding planner
1766,tt35146696,movie,Tu Meri Main Tera Main Tera Tu Meri,Tu Meri Main Tera Main Tera Tu Meri,0,2025,\N,145,"Adventure,Comedy,Romance",4.0,28166,2,nm9203528,actress,\N,Rumi,novelist
1547,tt21227864,movie,You're Cordially Invited,You're Cordially Invited,0,2025,\N,109,"Comedy,Romance",5.5,30685,1,nm0002071,actor,\N,Jim,unknown
1548,tt21227864,movie,You're Cordially Invited,You're Cordially Invited,0,2025,\N,109,"Comedy,Romance",5.5,30685,2,nm0000702,actress,\N,Margot,Tv producer

### Removing columns I don't need.

In [ ]:
romcoms_final.columns

Index(['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'isAdult',
       'startYear', 'endYear', 'runtimeMinutes', 'genres', 'averageRating',
       'numVotes', 'ordering', 'nconst', 'category', 'job', 'characters',
       'profession_final'],
      dtype='object')

In [ ]:
romcoms_final["profession_final"] = (
    romcoms_final["profession_final"]
    .str.lower()
)

In [ ]:
romcoms_final.to_csv("romcoms_analysis.csv")

In [ ]:
romcoms_final = pd.read_csv("romcoms_analysis.csv")
romcoms_final

,Unnamed: 0,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,ordering,nconst,category,job,characters,profession_final
0,12,tt0082477,movie,Gregory's Girl,Gregory's Girl,0,1980,\N,91,"Comedy,Drama,Romance",7.1,10068,1,nm0329947,actor,\N,Gregory,student
1,13,tt0082477,movie,Gregory's Girl,Gregory's Girl,0,1980,\N,91,"Comedy,Drama,Romance",7.1,10068,2,nm0378342,actress,\N,Dorothy,student
2,2,tt0079579,movie,Moscow Does Not Believe in Tears,Moskva slezam ne verit,0,1980,\N,150,"Comedy,Drama,Romance",8.0,15813,1,nm0018079,actress,\N,Katerina 'Katya' Tikhomirova,manufacturing worker
3,3,tt0079579,movie,Moscow Does Not Believe in Tears,Moskva slezam ne verit,0,1980,\N,150,"Comedy,Drama,Romance",8.0,15813,2,nm0060692,actor,\N,Georgiy 'Gosha',factory worker
4,6,tt0081480,movie,Seems Like Old Times,Seems Like Old Times,0,1980,\N,102,"Comedy,Romance",6.7,11862,1,nm0000443,actress,\N,Glenda Parks,lawyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1844,1750,tt33039440,movie,The Wrong Paris,The Wrong Paris,0,2025,\N,105,"Comedy,Drama,Romance",6.1,14590,2,nm4943457,actor,\N,Trey McAllen,rancher
1845,1765,tt35146696,movie,Tu Meri Main Tera Main Tera Tu Meri,Tu Meri Main Tera Main Tera Tu Meri,0,2025,\N,145,"Adventure,Comedy,Romance",4.0,28166,1,nm4449711,actor,\N,Ray,wedding planner
1846,1766,tt35146696,movie,Tu Meri Main Tera Main Tera Tu Meri,Tu Meri Main Tera Main Tera Tu Meri,0,2025,\N,145,"Adventure,Comedy,Romance",4.0,28166,2,nm9203528,actress,\N,Rumi,novelist
1847,1547,tt21227864,movie,You're Cordially Invited,You're Cordially Invited,0,2025,\N,109,"Comedy,Romance",5.5,30685,1,nm0002071,actor,\N,Jim,unknown
1848,1548,tt21227864,movie,You're Cordially Invited,You're Cordially Invited,0,2025,\N,109,"Comedy,Romance",5.5,30685,2,nm0000702,actress,\N,Margot,tv producer

#### Count films by release year and group them into decades for the chart

In [ ]:
romcoms_final.groupby("startYear")["primaryTitle"].nunique()

startYear
1980     5
1981     1
1982     4
1983     4
1984     6
1985     8
1986     8
1987    12
1988    11
1989     5
1990    10
1991    11
1992    15
1993    11
1994    16
1995    17
1996    14
1997    14
1998    14
1999    29
2000    22
2001    22
2002    24
2003    20
2004    34
2005    28
2006    36
2007    36
2008    39
2009    31
2010    42
2011    37
2012    32
2013    24
2014    37
2015    26
2016    20
2017    17
2018    26
2019    20
2020    23
2021    16
2022    29
2023    22
2024    19
2025    18
Name: primaryTitle, dtype: int64

In [ ]:
romcoms_final["decade"] = (romcoms_final["startYear"] // 10) * 10
romcoms_final.groupby("decade")["primaryTitle"].nunique()

decade
1980     64
1990    151
2000    291
2010    281
2020    127
Name: primaryTitle, dtype: int64

In [ ]:
romcoms_final["profession_final"].value_counts().head(11)

profession_final
student          337
businessman      110
unknown           89
teacher           64
writer            54
journalist        43
lawyer            43
businesswoman     26
architect         25
doctor            22
chef              20
Name: count, dtype: int64

In [ ]:
romcoms_final["profession_final"].nunique()

497

In [ ]:
(
    romcoms_final
    .query("category == 'actress'")
    ["profession_final"]
    .value_counts()
    .head(11)
)

profession_final
student          187
unknown           62
teacher           39
journalist        30
businesswoman     24
lawyer            21
waitress          20
writer            18
actress           14
homemaker         14
socialite         11
Name: count, dtype: int64

In [ ]:
(
    romcoms_final
    .query("category == 'actor'")
    ["profession_final"]
    .value_counts()
    .head(11)
)

profession_final
student         150
businessman     109
writer           36
unknown          27
teacher          23
lawyer           22
architect        18
doctor           14
actor            13
journalist       13
photographer     12
Name: count, dtype: int64

In [ ]:
romcoms_final.head()

,Unnamed: 0,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,ordering,nconst,category,job,characters,profession_final,decade
0,12,tt0082477,movie,Gregory's Girl,Gregory's Girl,0,1980,\N,91,"Comedy,Drama,Romance",7.1,10068,1,nm0329947,actor,\N,Gregory,student,1980
1,13,tt0082477,movie,Gregory's Girl,Gregory's Girl,0,1980,\N,91,"Comedy,Drama,Romance",7.1,10068,2,nm0378342,actress,\N,Dorothy,student,1980
2,2,tt0079579,movie,Moscow Does Not Believe in Tears,Moskva slezam ne verit,0,1980,\N,150,"Comedy,Drama,Romance",8.0,15813,1,nm0018079,actress,\N,Katerina 'Katya' Tikhomirova,manufacturing worker,1980
3,3,tt0079579,movie,Moscow Does Not Believe in Tears,Moskva slezam ne verit,0,1980,\N,150,"Comedy,Drama,Romance",8.0,15813,2,nm0060692,actor,\N,Georgiy 'Gosha',factory worker,1980
4,6,tt0081480,movie,Seems Like Old Times,Seems Like Old Times,0,1980,\N,102,"Comedy,Romance",6.7,11862,1,nm0000443,actress,\N,Glenda Parks,lawyer,1980