In [11]:
import pandas as pd

### Second manual review

#### After working through several intermediate CSV files, I realized I had lost track of the different versions of the dataset. Rather than continuing from an uncertain state, I performed one final manual review. 

#### This allowed me to remove a few more films that were not actually romantic comedies, make the last data corrections, and extract the final numbers used in the project.

In [58]:
df = pd.read_csv("romcoms_analysis_check.csv", sep=";")
df

,Unnamed: 0,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,category,characters,profession_final
0,12,tt0082477,movie,Gregory's Girl,Gregory's Girl,1980,91,"Comedy,Drama,Romance",7.1,10068,actor,Gregory,student
1,13,tt0082477,movie,Gregory's Girl,Gregory's Girl,1980,91,"Comedy,Drama,Romance",7.1,10068,actress,Dorothy,student
2,2,tt0079579,movie,Moscow Does Not Believe in Tears,Moskva slezam ne verit,1980,150,"Comedy,Drama,Romance",8.0,15813,actress,Katerina 'Katya' Tikhomirova,manufacturing worker
3,3,tt0079579,movie,Moscow Does Not Believe in Tears,Moskva slezam ne verit,1980,150,"Comedy,Drama,Romance",8.0,15813,actor,Georgiy 'Gosha',factory worker
4,6,tt0081480,movie,Seems Like Old Times,Seems Like Old Times,1980,102,"Comedy,Romance",6.7,11862,actress,Glenda Parks,lawyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1894,1750,tt33039440,movie,The Wrong Paris,The Wrong Paris,2025,105,"Comedy,Drama,Romance",6.1,14590,actor,Trey McAllen,rancher
1895,1765,tt35146696,movie,Tu Meri Main Tera Main Tera Tu Meri,Tu Meri Main Tera Main Tera Tu Meri,2025,145,"Adventure,Comedy,Romance",4.0,28166,actor,Ray,wedding planner
1896,1766,tt35146696,movie,Tu Meri Main Tera Main Tera Tu Meri,Tu Meri Main Tera Main Tera Tu Meri,2025,145,"Adventure,Comedy,Romance",4.0,28166,actress,Rumi,novelist
1897,1547,tt21227864,movie,You're Cordially Invited,You're Cordially Invited,2025,109,"Comedy,Romance",5.5,30685,actor,Jim,unknown
1898,1548,tt21227864,movie,You're Cordially Invited,You're Cordially Invited,2025,109,"Comedy,Romance",5.5,30685,actress,Margot,tv producer

In [59]:
remove_titles = [
    # 1980s
    "Barfly",
    "Hope and Glory",
    "New York Stories",
    "The Bonfire of the Vanities",
    "Weird Science",

    # 1990s
    "All About My Mother",
    "Beautiful Girls",
    "Election",
    "Home for the Holidays",
    "How to Make an American Quilt",
    "Life Is Beautiful",
    "Sweet and Lowdown",
    "The Wood",
    "Three Colors: White",

    # 2000s
    "Extract",
    "Factotum",
    "Friends with Money",
    "Good Bye, Lenin!",
    "Last Life in the Universe",
    "Man of the Year",
    "Smart People",
    "Solitary Man",
    "Storytelling",
    "The History Boys",
    "The Private Lives of Pippa Lee",
    "Up in the Air",
    "Venus",

    # 2010s
    "50/50",
    "Charlie Countryman",
    "Fading Gigolo",
    "Hello, My Name Is Doris",
    "Infinitely Polar Bear",
    "Paterson",
    "People Places Things",
    "Somewhere",
    "The Artist",
    "The Meddler",
    "The Romantics",
    "The Rum Diary",
    "Their Finest",
    "Tiny Furniture",
    "You Will Meet a Tall Dark Stranger",

    # 2020s
    "Afire",
    "Am I OK?",
    "Asteroid City",
    "Babyteeth",
    "Bergman Island",
    "Dil Bechara",
    "Fallen Leaves",
    "Flora and Son",
    "Fresh",
    "Good Grief",
    "Kho Gaye Hum Kahan",
    "My Favourite Cake",
    "On the Rocks",
    "Paris, 13th District",
    "Poor Things",
    "Red Rocket",
    "The Worst Person in the World",
    "You Hurt My Feelings"
]

In [60]:
df_final = df[
    ~df["primaryTitle"].isin(remove_titles)
]

In [61]:
df_final.shape

(1781, 13)

In [69]:
df_final["tconst"].nunique()

882

In [111]:
df_final.groupby("decade")["tconst"].nunique()

decade
1980     64
1990    146
2000    293
2010    264
2020    115
Name: tconst, dtype: int64

In [112]:
(
    df_final
    .groupby("primaryTitle")["startYear"]
    .unique()
    .loc[lambda s: s.str.len() > 1]
)

primaryTitle
About Last Night          [1986, 2014]
Arthur                    [1981, 2011]
Barefoot                  [2005, 2014]
Cocktail                  [1988, 2012]
Father of the Bride       [1991, 2022]
Fever Pitch               [1997, 2005]
Much Ado About Nothing    [1993, 2012]
My Sassy Girl             [2001, 2008]
Overboard                 [1987, 2018]
Name: startYear, dtype: object

In [113]:
df_final["profession_final"].value_counts().head(11)

profession_final
student          325
businessman      109
unknown           96
teacher           59
lawyer            44
writer            43
journalist        43
businesswoman     25
architect         25
doctor            23
waitress          22
Name: count, dtype: int64

In [114]:
(
    df_final
    .query("category == 'actress'")
    ["profession_final"]
    .value_counts()
    .head(11)
)

profession_final
student          180
unknown           65
teacher           38
journalist        30
businesswoman     25
waitress          22
lawyer            21
writer            15
homemaker         12
socialite         11
actress           11
Name: count, dtype: int64

In [115]:
(
    df_final
    .query("category == 'actor'")
    ["profession_final"]
    .value_counts()
    .head(11)
)

profession_final
student        145
businessman    109
unknown         31
writer          28
lawyer          23
teacher         19
architect       18
doctor          14
journalist      13
unemployed      12
actor           11
Name: count, dtype: int64

In [116]:
df_final["decade"] = (df_final["startYear"] // 10) * 10
df_final.groupby("decade")["primaryTitle"].nunique()

/var/folders/qn/0_m8lc7j6hz111kp72r17lnh0000gn/T/ipykernel_14752/2477616491.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["decade"] = (df_final["startYear"] // 10) * 10

decade
1980     64
1990    146
2000    292
2010    264
2020    115
Name: primaryTitle, dtype: int64

In [117]:
df_final.head()

,Unnamed: 0,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,category,characters,profession_final,decade
0,12,tt0082477,movie,Gregory's Girl,Gregory's Girl,1980,91,"Comedy,Drama,Romance",7.1,10068,actor,Gregory,student,1980
1,13,tt0082477,movie,Gregory's Girl,Gregory's Girl,1980,91,"Comedy,Drama,Romance",7.1,10068,actress,Dorothy,student,1980
2,2,tt0079579,movie,Moscow Does Not Believe in Tears,Moskva slezam ne verit,1980,150,"Comedy,Drama,Romance",8.0,15813,actress,Katerina 'Katya' Tikhomirova,manufacturing worker,1980
3,3,tt0079579,movie,Moscow Does Not Believe in Tears,Moskva slezam ne verit,1980,150,"Comedy,Drama,Romance",8.0,15813,actor,Georgiy 'Gosha',factory worker,1980
4,6,tt0081480,movie,Seems Like Old Times,Seems Like Old Times,1980,102,"Comedy,Romance",6.7,11862,actress,Glenda Parks,lawyer,1980

In [118]:
df_final.to_csv("romcoms_finished.csv")